// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RequestLog struct {
	ID              pgtype.UUID
	Timestamp       pgtype.Timestamptz
	Method          string
	IncomingPath    string
	RedirectedPath  pgtype.Text
	UserID          pgtype.Text
	Realm           pgtype.Text
	StatusCode      int32
	ResponseTimeMs  int32
	UpstreamService pgtype.Text
	ErrorMessage    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}
