// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStudentByUuid = `-- name: GetStudentByUuid :one
select uuid, first_name, middle_name, last_name, personal_number, fathers_name, mothers_name, date_of_birth, place_of_residence, place_of_birth, citizenship, school_uuid from student
where uuid = $1
`

func (q *Queries) GetStudentByUuid(ctx context.Context, studentUuid pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUuid, studentUuid)
	var i Student
	err := row.Scan(
		&i.Uuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.PersonalNumber,
		&i.FathersName,
		&i.MothersName,
		&i.DateOfBirth,
		&i.PlaceOfResidence,
		&i.PlaceOfBirth,
		&i.Citizenship,
		&i.SchoolUuid,
	)
	return i, err
}
