// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teacher.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTeacher = `-- name: InsertTeacher :one
insert into teacher (school_uuid, first_name, middle_name, last_name, clerk_id)
values ($1, $2, $3, $4, $5)
returning uuid, school_uuid, first_name, middle_name, last_name, print_allowed, clerk_id
`

type InsertTeacherParams struct {
	SchoolUuid pgtype.UUID
	FirstName  string
	MiddleName pgtype.Text
	LastName   string
	ClerkID    string
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, insertTeacher,
		arg.SchoolUuid,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.ClerkID,
	)
	var i Teacher
	err := row.Scan(
		&i.Uuid,
		&i.SchoolUuid,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.PrintAllowed,
		&i.ClerkID,
	)
	return i, err
}
